Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  NODES = {
    "master"  => { ip: "192.168.122.10", memory: 2048, cpus: 2 },
    "worker1" => { ip: "192.168.122.11", memory: 2048, cpus: 2 },
    "worker2" => { ip: "192.168.122.12", memory: 2048, cpus: 2 },
    "worker3" => { ip: "192.168.122.13", memory: 2048, cpus: 2 },
  }

  NODES.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = name

      node.vm.network "private_network",
        ip: opts[:ip],
        libvirt__network_name: "default"

      node.vm.provider :libvirt do |lv|
        lv.memory = opts[:memory]
        lv.cpus   = opts[:cpus]
      end

      node.vm.provision "shell", inline: <<-SHELL
        echo "127.0.0.1 #{name}" >> /etc/hosts
      SHELL
    end
  end
end
